salario = float(input('Quanto você ganha por hora? '))
nHoras = float(input('numero de horas trabalhadas no mês: '))
salarioB = (salario*nHoras)
ImpostoRenda = (salarioB*0.11)
INSS = (salarioB*0.08)
sindicato = (salarioB*0.05)
salarioL = (salarioB-(salarioB*0.24))
print ('salario bruto:R$',salarioB)
print ('INSS(11%):R$',INSS)
print ('Sindicato(5%):R$',sindicato)
print ('IR(11%):R$',ImpostoRenda)
print ('salario liquido:R$',salarioL)
