n1 = int (input('primeiro numero '))
n2 = int (input('segundo numero '))
n3 = float (input('terceiro numero '))
a = ((n1*2)*(n2/2))
b = ((n1*3)+ n3)
c = (n3**3)
print ('o produto...',a)
print ('a soma...',b)
print ('ao cubo...',c)
